FROM apache/airflow:2.10.2-python3.9

# Set working directory
WORKDIR /opt/airflow

# Install system dependencies as root
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    libpq-dev \
    postgresql-client \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy CA certificate and entrypoint script
COPY ca.pem /ca.pem
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Switch to airflow user
USER airflow

# Install Python dependencies
COPY airflow_scheduler_service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Django project and Airflow DAGs
COPY airflow_scheduler_service ./airflow_scheduler_service
COPY dags ./dags

# Set environment variables for Airflow
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False
ENV AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags

# Expose Airflow webserver port
EXPOSE 8080

# Use custom entrypoint
ENTRYPOINT ["/entrypoint.sh"]