FROM apache/airflow:2.10.2-python3.9

# Set working directory
WORKDIR /opt/airflow

# Install system dependencies as root
USER root
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    && apt-get clean

# Copy entrypoint script and make it executable as root
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Switch to airflow user for remaining operations
USER airflow

# Install Python dependencies
COPY airflow_scheduler_service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Django project and Airflow DAGs
COPY airflow_scheduler_service ./airflow_scheduler_service
COPY dags ./dags

# Set environment variables for Airflow
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False
ENV AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
ENV AIRFLOW__SCHEDULER__SCHEDULE_INTERVAL=300

# Expose Airflow webserver and scheduler ports
EXPOSE 8080

# Use custom entrypoint to initialize Airflow
ENTRYPOINT ["/entrypoint.sh"]